# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# production:
#   host: aws-us-east-1-portal.9.dblayer.com
#   auth_key: TDIcsArmP5uZ972DtNlkH2LCQOHob8rYpuLvoZJv8
#   cacert: "MIIDYzCCAkugAwIBAgIEV7SiUjANBgkqhkiG9w0BAQ0FADAzMTEwLwYDVQQDDChWZXJpdGFzLWQwYTQyOTFjZDZmNWNkZjUwZDg3NTljNmUwNzcyMjZmMB4XDTE2MDgxNzE3NDM0NloXDTM2MDgxNzE3MDAwMFowMzExMC8GA1UEAwwoVmVyaXRhcy1kMGE0MjkxY2Q2ZjVjZGY1MGQ4NzU5YzZlMDc3MjI2ZjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANA3sH+WG3uF3NRS2TEbfDivxdfguHcz1V4A8OXrPPj3buNLjZa+3UyDILSgE5F6rNSZk020qFosNpEMX3W6vQ7faicAco919chn/E9pbZSoPkagmzj3+jiHbQKY5f/CoveGl/OocOXO6gvzo90xTx1Ixpmwg3FCLWDpVTHf6lT7qiClWLzjqrhOKLVQK8zMrcm24Eb5xFQKbtKDjJpdKZlXQuZaJ+cLEOZYs+rFmJvToDoeE4TCLBXjFY+Qh99IR5sIhIHgSF/8D0Pi2VOv2uFJtLhe2r/qtkA8KhP34jmN1es+ThlXnjYaN5H43HsQJ7FFubfPvbiyP695+blDe9MCAwEAAaN/MH0wHQYDVR0OBBYEFB8Dr4lYGltt6b5a4R4CK/2Lw4TvMA4GA1UdDwEB/wQEAwICBDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TBAUwAwEB/zAfBgNVHSMEGDAWgBQfA6+JWBpbbem+WuEeAiv9i8OE7zANBgkqhkiG9w0BAQ0FAAOCAQEAe0r0rY8b3YHgd10LkQ+jXXMEn1HLW8ji8ybly/sBUoppYt2/e4Ca8vn9G1+J1j8jM0R/FlSHct5vMcTUMtePL3eRBbB00x+hQ5jk+ICu4kz+DdHWnveKCB/Q52YbEMtpwqxTKDfocR03UkHFuDD2LNACI92aq8prT5bq7YRqNkCSfLbq+KMMo563GXFyFEQxXyQUeQdnXa8VSp4HY0mf3xLWgh6vBDuZ/35hC13EyfjsOkSEarrJNVC9B45R+Pm6tCudcDFh0ULnEEmEvtxSySMyLgJWU6LpEq+XUk/+r8jnzRum+IIceNjsrQz0hYil0fwu2UYK7LZzV2ufGa3wCQ=="

production:
  S3_KEY: "AKIAIEHXBEJTIZHBO6VA"
  S3_SECRET: "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"
  S3_BUCKET_NAME: "gopost-test"
  AWS_REGION: "us-west-1"
development:
  S3_KEY: "AKIAIEHXBEJTIZHBO6VA"
  S3_SECRET: "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"
  S3_BUCKET_NAME: "gopost-test"
  AWS_REGION: "us-west-1"
  MONGODB_URI: "mongodb://tedma4:tm671216@ds133428.mlab.com:33428/veritas_db"
  gmail_email: "tedma4"
  gmail_password: "tm671216"
  my_jwt: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzZXJfaWQiOiI1ODU2ZDc3M2MyMzgyZjQxNTA4MWU4Y2QifX0.n1M4O42fF86xLIzIZbCf3m9anMTX4P2i2bktrnooq9M"
  taylors_jwt: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzZXJfaWQiOiI1ODU3MTZmNGMyOTE2MzAwMDQwNmZmODYifX0.zMaJrm5FR1H8GbBNT8ICYV_0UyvieP7NPVqmIH-g4iU"
  vinis_jwt: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7InVzZXJfaWQiOiI1ODU3NGZkMTEwZGVkNDAwMDRjOTU2ZGMifX0.q8e4EcVOkBTHFAvLMJf2US5NpYlr0ytKLg6M_KFnCPg"
  place_key: 'AIzaSyAU7vv1IU0p7UKr8YiKASuKXKn7ptBrcUk'




# heroku config:add S3_KEY=AKIAIEHXBEJTIZHBO6VA S3_SECRET=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 S3_BUCKET_NAME=gopost-test/posts
